language: en
saveIntervallInSeconds: 10
banOnDeath: true
secondChance: true
secondChanceTime: 120
enableMySQL: true
mysql:
   host: 85.131.156.196
   port: 3306
   database: ni4078_1_DB
   username: ni4078_1_DB
   password: qpyZ7yS7
en:
   day: "day"
   days: "days"
   hour: "hour"
   hours: "hours"
   minute: "minute"
   minutes: "minutes"
   second: "second"
   seconds: "seconds"
   playerDies: "You died :("
   luck: "Good luck for the next try!"
   playerNotOnServer: "Player wasn't on the server!"
   pleaseConfirm: "Please confirm reset of Player "
   withresetConfirm: "with /reset confirm "
   confirmCodeWrong: "confirmcode wrong, please try again. "
   playTime: "Your playtime: "
   noPermission: "You don't have the permission to do that!"
   secondChance: "You got a second Chance, don't be careful this time!"
de:
   day: "Tag"
   days: "Tage"
   hour: "Stunde"
   hours: "Stunden"
   minute: "Minute"
   minutes: "Minuten"
   second: "Sekunde"
   seconds: "Sekunden"
   playerDies: "Du bist gestorben :("
   luck: "Viel Glueck beim naechsten Mal!"
   playerNotOnServer: "Spieler war nicht auf dem Server!"
   pleaseConfirm: "Bitte bestaetige den reset vom Spieler "
   withresetConfirm: "mit /reset confirm "
   confirmCodeWrong: "Bestaetigungscode war falsch. "
   playTime: "Deine Spielzeit: "
   noPermission: "Du hast nicht die noetigen Rechte dafuer!"
   secondChance: "Du hast eine zweite Chance erhalten, sei vorsichtiger!"

